apiVersion: apps/v1
kind: Deployment
metadata:
  name: niraxo-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: niraxo-website
  template:
    metadata:
      labels:
        app: niraxo-website
    spec:
      containers:
        - name: niraxo-website
          image: 726655177496.dkr.ecr.ap-south-1.amazonaws.com/niraxo/frontend-website:10046-20260205143102
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 60m
              memory: 60Mi
            limits:
              memory: 500Mi
      nodeSelector:
        workload: application
      tolerations:
        - key: "karpenter.sh/workload"
          operator: "Equal"
          value: "application"
          effect: "NoSchedule" 
