apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: niraxo-website-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: niraxo-website
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
      - containerName: niraxo-website
        controlledResources:
          - memory
        minAllowed:
          memory: 30Mi
        maxAllowed:
          memory: 20Gi

